# Anexos

- El repositorio en GitHub incluye un archivo ZIP en el siguiente enlace (https://raw.githubusercontent.com/smramirezb/datos_ejemplos/refs/heads/main/informe.zip) con los ficheros fuente de bookdown para reproducir el informe:

  - `index_a.Rmd`
  - `descripcion_actividad_a.Rmd`
  - `objetivos_a.Rmd`
  - `datos_a.Rmd`
  - `procesamiento_a.Rmd`
  - `resultados_a.Rmd`
  - `conclusiones_a.Rmd`
  - `referencias_a.Rmd`
  - `Anexos_a.Rmd`
  - `_bookdown.yml`

- Para compilar el informe completo:

  - Abra el proyecto en **RStudio** (haga doble clic en `proyecto.Rproj`).
  - En la consola de **R**, ejecute `bookdown::render_book("index_a.Rmd")`
 
- Los archivos HTML generados se guardan en la carpeta `docs/`, con los siguientes nombres:
  
  - `index_a.html`
  - `descripcion_actividad_a.html`
  - `objetivos_a.html`
  - `datos_a.html`
  - `procesamiento_a.html`
  - `resultados_a.html`
  - `conclusiones_a.html`
  - `referencias_a.html`
  - `Anexos_a.html`
  
  
- El archivo `index_a.html` es la página principal que agrupa todo el contenido del informe. 

