<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5 Procesamiento | Informe-descriptivo</title>
  <meta name="description" content="5 Procesamiento | Informe-descriptivo" />
  <meta name="generator" content="bookdown 0.42 and GitBook 2.6.7" />

  <meta property="og:title" content="5 Procesamiento | Informe-descriptivo" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5 Procesamiento | Informe-descriptivo" />
  
  
  

<meta name="author" content="Centromagis" />


<meta name="date" content="2025-05-13" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="datos.html"/>
<link rel="next" href="resultados.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>



<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="índice.html"><a href="índice.html"><i class="fa fa-check"></i><b>1</b> Índice</a></li>
<li class="chapter" data-level="2" data-path="descripción.html"><a href="descripción.html"><i class="fa fa-check"></i><b>2</b> Descripción</a></li>
<li class="chapter" data-level="3" data-path="objetivos.html"><a href="objetivos.html"><i class="fa fa-check"></i><b>3</b> Objetivos</a>
<ul>
<li class="chapter" data-level="3.1" data-path="objetivos.html"><a href="objetivos.html#objetivo-general"><i class="fa fa-check"></i><b>3.1</b> Objetivo general</a></li>
<li class="chapter" data-level="3.2" data-path="objetivos.html"><a href="objetivos.html#objetivo-específicos"><i class="fa fa-check"></i><b>3.2</b> Objetivo específicos</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="datos.html"><a href="datos.html"><i class="fa fa-check"></i><b>4</b> Datos</a></li>
<li class="chapter" data-level="5" data-path="procesamiento.html"><a href="procesamiento.html"><i class="fa fa-check"></i><b>5</b> Procesamiento</a>
<ul>
<li class="chapter" data-level="5.1" data-path="procesamiento.html"><a href="procesamiento.html#errores-e-inconsistencias"><i class="fa fa-check"></i><b>5.1</b> Errores e inconsistencias</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="procesamiento.html"><a href="procesamiento.html#errores-de-escritura"><i class="fa fa-check"></i><b>5.1.1</b> Errores de escritura</a></li>
<li class="chapter" data-level="5.1.2" data-path="procesamiento.html"><a href="procesamiento.html#inconsistencias"><i class="fa fa-check"></i><b>5.1.2</b> Inconsistencias</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="procesamiento.html"><a href="procesamiento.html#análisis-de-datos-atípicos"><i class="fa fa-check"></i><b>5.2</b> Análisis de datos atípicos</a></li>
<li class="chapter" data-level="5.3" data-path="procesamiento.html"><a href="procesamiento.html#identificación-de-datos-faltantes"><i class="fa fa-check"></i><b>5.3</b> Identificación de datos faltantes</a></li>
<li class="chapter" data-level="5.4" data-path="procesamiento.html"><a href="procesamiento.html#imputación-de-datos-faltantes"><i class="fa fa-check"></i><b>5.4</b> Imputación de datos faltantes</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="procesamiento.html"><a href="procesamiento.html#imputación-del-precio-price"><i class="fa fa-check"></i><b>5.4.1</b> Imputación del Precio (price)</a></li>
<li class="chapter" data-level="5.4.2" data-path="procesamiento.html"><a href="procesamiento.html#imputación-de-la-edad-age"><i class="fa fa-check"></i><b>5.4.2</b> Imputación de la Edad (age)</a></li>
<li class="chapter" data-level="5.4.3" data-path="procesamiento.html"><a href="procesamiento.html#imputación-de-sexo-gender-centro-comercial-shopping_mall-y-método-de-pago-payment_method"><i class="fa fa-check"></i><b>5.4.3</b> Imputación de Sexo (gender), Centro Comercial (shopping_mall) y Método de pago (payment_method)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="resultados.html"><a href="resultados.html"><i class="fa fa-check"></i><b>6</b> Resultados</a>
<ul>
<li class="chapter" data-level="6.1" data-path="resultados.html"><a href="resultados.html#características-demográficas-de-los-consumidores"><i class="fa fa-check"></i><b>6.1</b> Características demográficas de los consumidores</a></li>
<li class="chapter" data-level="6.2" data-path="resultados.html"><a href="resultados.html#preferencia-de-productos-de-acuerdo-con-edad-y-sexo"><i class="fa fa-check"></i><b>6.2</b> Preferencia de productos de acuerdo con edad y sexo</a></li>
<li class="chapter" data-level="6.3" data-path="resultados.html"><a href="resultados.html#métodos-de-pago-de-acuerdo-con-edad-sexo-y-tipo-de-producto"><i class="fa fa-check"></i><b>6.3</b> Métodos de pago de acuerdo con edad, sexo y tipo de producto</a></li>
<li class="chapter" data-level="6.4" data-path="resultados.html"><a href="resultados.html#monto-total-de-transacción-de-acuerdo-con-edad-sexo-y-tipo-de-producto"><i class="fa fa-check"></i><b>6.4</b> Monto total de transacción de acuerdo con edad, sexo y tipo de producto</a></li>
<li class="chapter" data-level="6.5" data-path="resultados.html"><a href="resultados.html#distribución-del-consumo-en-centros-comerciales"><i class="fa fa-check"></i><b>6.5</b> Distribución del consumo en centros comerciales</a></li>
<li class="chapter" data-level="6.6" data-path="resultados.html"><a href="resultados.html#tendencia-de-consumo-por-centro-comercial-en-el-periodo-muestreado"><i class="fa fa-check"></i><b>6.6</b> Tendencia de consumo por centro comercial en el periodo muestreado</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="conclusiones.html"><a href="conclusiones.html"><i class="fa fa-check"></i><b>7</b> Conclusiones</a></li>
<li class="chapter" data-level="8" data-path="referencias.html"><a href="referencias.html"><i class="fa fa-check"></i><b>8</b> Referencias</a></li>
<li class="chapter" data-level="9" data-path="anexos.html"><a href="anexos.html"><i class="fa fa-check"></i><b>9</b> Anexos</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Informe-descriptivo</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="procesamiento" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">5</span> Procesamiento<a href="procesamiento.html#procesamiento" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="errores-e-inconsistencias" class="section level2 hasAnchor" number="5.1">
<h2><span class="header-section-number">5.1</span> Errores e inconsistencias<a href="procesamiento.html#errores-e-inconsistencias" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="errores-de-escritura" class="section level3 hasAnchor" number="5.1.1">
<h3><span class="header-section-number">5.1.1</span> Errores de escritura<a href="procesamiento.html#errores-de-escritura" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>En la primera etapa del preprocesamiento de los datos, se procedió a la estandarización de la notación utilizada en las categorías de las variables <em>Sexo</em>, <em>Categoría</em> y <em>Método de pago</em>. Estas variables presentaban inconsistencias tipográficas al representar una misma categoría. Por ejemplo, en la variable <em>Sexo</em> se encontraron notaciones como <code>"female"</code> y <code>"Female"</code>, así como <code>"male"</code> y <code>"Male"</code>, los cuales debían ser tratados como equivalentes. De manera similar, en la variable <em>Categoría</em> se identificaron registros como <code>"clothing"</code> y <code>"Clothing"</code>, <code>"cosmetics"</code> y <code>"Cosmetics"</code>, así como <code>"toys"</code>, <code>"Toys"</code> y <code>"ToyS"</code>, todos ellos correspondientes a una misma categoría conceptual. En el caso de la variable <em>Método de pago</em>, se observaron valores como <code>"cash"</code> y <code>"Cash"</code>, además de <code>"debit card"</code> y <code>"Debit card"</code>, que remiten a una misma modalidad de pago. Estas inconsistencias fueron corregidas mediante la transformación a notación estandarizada en minúsculas.</p>
</div>
<div id="inconsistencias" class="section level3 hasAnchor" number="5.1.2">
<h3><span class="header-section-number">5.1.2</span> Inconsistencias<a href="procesamiento.html#inconsistencias" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="identificadores-de-facturas" class="section level4 hasAnchor" number="5.1.2.1">
<h4><span class="header-section-number">5.1.2.1</span> Identificadores de facturas<a href="procesamiento.html#identificadores-de-facturas" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>En una segunda etapa, se verificó la unicidad de los identificadores de facturas, considerando que, en términos generales, un número de factura no debería repetirse dentro de un mismo sistema de facturación, dado que su función principal es permitir la identificación única de cada transacción registrada, tanto para fines internos como fiscales. No obstante, es posible que un mismo identificador aparezca en múltiples filas cuando cada una representa un producto distinto incluido en la misma factura. Sin embargo, este no fue el caso en el presente conjunto de datos.</p>
<p>Durante la revisión de los identificadores de factura, se detectaron nueve registros duplicados, en los cuales el mismo número de factura estaba asociado a diferentes fechas y clientes. De estos duplicados, siete coincidían completamente en la información relacionada con el cliente y la transacción realizada, lo que indicó la presencia de duplicados exactos. Como resultado, se eliminaron siete de estos registros, dejando solo uno por factura. Además, se identificaron dos facturas duplicadas debido a errores en la asignación de identificadores, lo que afectó a cuatro registros. A estos registros se les asignaron nuevos identificadores únicos: <code>"i000000"</code>, <code>"i111111"</code>, <code>"i222222"</code> y <code>"i333333"</code>. Como consecuencia de este proceso, se eliminaron 7 registros, quedando un total de 99,459 transacciones para continuar con el análisis.</p>
<p>En una tercera etapa se analizaron posibles errores y valores atípicos en las variables cuantitativas: Edad, precio y cantidad del producto.</p>
</div>
<div id="edad" class="section level4 hasAnchor" number="5.1.2.2">
<h4><span class="header-section-number">5.1.2.2</span> Edad<a href="procesamiento.html#edad" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>La Figura <a href="procesamiento.html#fig:fig-edad">5.1</a> evidencia que la variable <em>Edad</em> no presenta valores atípicos. Este hallazgo se corrobora con la Tabla <a href="procesamiento.html#tab:tabla-edad">5.1</a>, la cual muestra las estadísticas descriptivas de la variable Edad y revela que el rango de edades, de 18 a 69 años, es coherente y plausible para los identificadores de compra.</p>
<div class="figure"><span style="display:block;" id="fig:fig-edad"></span>
<img src="Informe-descriptivo_files/figure-html/fig-edad-1.png" alt="Edad (años)." width="672" />
<p class="caption">
Figure 5.1: Edad (años).
</p>
</div>
<table>
<caption><span id="tab:tabla-edad">Table 5.1: </span>Estadísticas de edad (años). Se presentan: n (número de registros); Q1 (primer cuartil); Q2 (mediana); Q3 (tercer cuartil); Min (mínimo); Max (máximo); Atm (atípicos inferiores); AtM (atípicos superiores); CV (coeficiente de variación).</caption>
<thead>
<tr class="header">
<th align="right">n</th>
<th align="right">Min</th>
<th align="right">Q1</th>
<th align="right">Q2</th>
<th align="right">Q3</th>
<th align="right">Max</th>
<th align="right">Atm</th>
<th align="right">AtM</th>
<th align="right">CV</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">99459</td>
<td align="right">18</td>
<td align="right">30</td>
<td align="right">43</td>
<td align="right">56</td>
<td align="right">69</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0.345</td>
</tr>
</tbody>
</table>
</div>
<div id="precio" class="section level4 hasAnchor" number="5.1.2.3">
<h4><span class="header-section-number">5.1.2.3</span> Precio<a href="procesamiento.html#precio" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>La Figura <a href="procesamiento.html#fig:fig-precio-todo">5.2</a> y la Tabla <a href="procesamiento.html#tab:tabla-precio-todo">5.2</a> evidencian distribuciones prácticamente idénticas del precio unitario por categoría de producto en los distintos centros comerciales. Para profundizar en las posibles diferencias, a continuación se analiza con detalle el precio de cada categoría de producto.</p>
<div class="figure"><span style="display:block;" id="fig:fig-precio-todo"></span>
<img src="Informe-descriptivo_files/figure-html/fig-precio-todo-1.png" alt="Distribución de precios por categoría y centro comercial." width="672" />
<p class="caption">
Figure 5.2: Distribución de precios por categoría y centro comercial.
</p>
</div>
<table>
<caption><span id="tab:tabla-precio-todo">Table 5.2: </span>Resumen del precio por categoría y centro comercial. Q1: primer cuartil; Mediana (Q2); Q3: tercer cuartil; Min: mínimo; Máx.: máximo; CV: coeficiente de variación.</caption>
<colgroup>
<col width="20%" />
<col width="23%" />
<col width="9%" />
<col width="9%" />
<col width="10%" />
<col width="9%" />
<col width="10%" />
<col width="7%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Categoría</th>
<th align="left">Centro comercial</th>
<th align="right">Mínimo</th>
<th align="right">Q1</th>
<th align="right">Mediana</th>
<th align="right">Q3</th>
<th align="right">Máx.</th>
<th align="right">CV</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">books</td>
<td align="left">cevahir avm</td>
<td align="right">303</td>
<td align="right">606</td>
<td align="right">1515</td>
<td align="right">4545</td>
<td align="right">7575</td>
<td align="right">0.94</td>
</tr>
<tr class="even">
<td align="left">books</td>
<td align="left">emaar square mall</td>
<td align="right">303</td>
<td align="right">606</td>
<td align="right">1515</td>
<td align="right">4545</td>
<td align="right">7575</td>
<td align="right">0.90</td>
</tr>
<tr class="odd">
<td align="left">books</td>
<td align="left">forum istanbul</td>
<td align="right">303</td>
<td align="right">606</td>
<td align="right">1515</td>
<td align="right">4545</td>
<td align="right">7575000</td>
<td align="right">14.49</td>
</tr>
<tr class="even">
<td align="left">books</td>
<td align="left">istinye park</td>
<td align="right">303</td>
<td align="right">606</td>
<td align="right">1515</td>
<td align="right">4545</td>
<td align="right">7575</td>
<td align="right">0.96</td>
</tr>
<tr class="odd">
<td align="left">books</td>
<td align="left">kanyon</td>
<td align="right">303</td>
<td align="right">606</td>
<td align="right">1515</td>
<td align="right">4545</td>
<td align="right">7575</td>
<td align="right">0.94</td>
</tr>
<tr class="even">
<td align="left">books</td>
<td align="left">mall of istanbul</td>
<td align="right">303</td>
<td align="right">606</td>
<td align="right">1515</td>
<td align="right">4545</td>
<td align="right">7575</td>
<td align="right">0.94</td>
</tr>
<tr class="odd">
<td align="left">books</td>
<td align="left">metrocity</td>
<td align="right">303</td>
<td align="right">606</td>
<td align="right">1515</td>
<td align="right">4545</td>
<td align="right">7575</td>
<td align="right">0.96</td>
</tr>
<tr class="even">
<td align="left">books</td>
<td align="left">metropol avm</td>
<td align="right">303</td>
<td align="right">606</td>
<td align="right">1515</td>
<td align="right">4545</td>
<td align="right">7575</td>
<td align="right">0.94</td>
</tr>
<tr class="odd">
<td align="left">books</td>
<td align="left">viaport outlet</td>
<td align="right">303</td>
<td align="right">606</td>
<td align="right">1515</td>
<td align="right">4545</td>
<td align="right">7575</td>
<td align="right">0.95</td>
</tr>
<tr class="even">
<td align="left">books</td>
<td align="left">zorlu center</td>
<td align="right">303</td>
<td align="right">606</td>
<td align="right">1515</td>
<td align="right">4545</td>
<td align="right">7575</td>
<td align="right">0.94</td>
</tr>
<tr class="odd">
<td align="left">clothing</td>
<td align="left">cevahir avm</td>
<td align="right">1</td>
<td align="right">30008</td>
<td align="right">60016</td>
<td align="right">90024</td>
<td align="right">120032</td>
<td align="right">0.62</td>
</tr>
<tr class="even">
<td align="left">clothing</td>
<td align="left">emaar square mall</td>
<td align="right">15004</td>
<td align="right">30008</td>
<td align="right">60016</td>
<td align="right">90024</td>
<td align="right">120032</td>
<td align="right">0.61</td>
</tr>
<tr class="odd">
<td align="left">clothing</td>
<td align="left">forum istanbul</td>
<td align="right">15004</td>
<td align="right">30008</td>
<td align="right">60016</td>
<td align="right">90024</td>
<td align="right">120032</td>
<td align="right">0.61</td>
</tr>
<tr class="even">
<td align="left">clothing</td>
<td align="left">istinye park</td>
<td align="right">15004</td>
<td align="right">30008</td>
<td align="right">60016</td>
<td align="right">90024</td>
<td align="right">120032</td>
<td align="right">0.61</td>
</tr>
<tr class="odd">
<td align="left">clothing</td>
<td align="left">kanyon</td>
<td align="right">15004</td>
<td align="right">30008</td>
<td align="right">60016</td>
<td align="right">90024</td>
<td align="right">120032</td>
<td align="right">0.61</td>
</tr>
<tr class="even">
<td align="left">clothing</td>
<td align="left">mall of istanbul</td>
<td align="right">15004</td>
<td align="right">30008</td>
<td align="right">60016</td>
<td align="right">90024</td>
<td align="right">120032</td>
<td align="right">0.61</td>
</tr>
<tr class="odd">
<td align="left">clothing</td>
<td align="left">metrocity</td>
<td align="right">15004</td>
<td align="right">30008</td>
<td align="right">60016</td>
<td align="right">90024</td>
<td align="right">120032</td>
<td align="right">0.60</td>
</tr>
<tr class="even">
<td align="left">clothing</td>
<td align="left">metropol avm</td>
<td align="right">2</td>
<td align="right">30008</td>
<td align="right">60016</td>
<td align="right">90024</td>
<td align="right">120032</td>
<td align="right">0.60</td>
</tr>
<tr class="odd">
<td align="left">clothing</td>
<td align="left">viaport outlet</td>
<td align="right">15004</td>
<td align="right">30008</td>
<td align="right">60016</td>
<td align="right">90024</td>
<td align="right">120032</td>
<td align="right">0.61</td>
</tr>
<tr class="even">
<td align="left">clothing</td>
<td align="left">zorlu center</td>
<td align="right">15004</td>
<td align="right">30008</td>
<td align="right">60016</td>
<td align="right">90024</td>
<td align="right">120032</td>
<td align="right">0.60</td>
</tr>
<tr class="odd">
<td align="left">cosmetics</td>
<td align="left">cevahir avm</td>
<td align="right">2033</td>
<td align="right">4066</td>
<td align="right">8132</td>
<td align="right">12198</td>
<td align="right">16264</td>
<td align="right">0.60</td>
</tr>
<tr class="even">
<td align="left">cosmetics</td>
<td align="left">emaar square mall</td>
<td align="right">2033</td>
<td align="right">4066</td>
<td align="right">8132</td>
<td align="right">12198</td>
<td align="right">16264</td>
<td align="right">0.62</td>
</tr>
<tr class="odd">
<td align="left">cosmetics</td>
<td align="left">forum istanbul</td>
<td align="right">2033</td>
<td align="right">4066</td>
<td align="right">8132</td>
<td align="right">12198</td>
<td align="right">16264</td>
<td align="right">0.62</td>
</tr>
<tr class="even">
<td align="left">cosmetics</td>
<td align="left">istinye park</td>
<td align="right">2033</td>
<td align="right">4066</td>
<td align="right">8132</td>
<td align="right">12198</td>
<td align="right">16264</td>
<td align="right">0.60</td>
</tr>
<tr class="odd">
<td align="left">cosmetics</td>
<td align="left">kanyon</td>
<td align="right">2033</td>
<td align="right">4066</td>
<td align="right">8132</td>
<td align="right">12198</td>
<td align="right">16264</td>
<td align="right">0.61</td>
</tr>
<tr class="even">
<td align="left">cosmetics</td>
<td align="left">mall of istanbul</td>
<td align="right">2033</td>
<td align="right">4066</td>
<td align="right">8132</td>
<td align="right">12198</td>
<td align="right">16264</td>
<td align="right">0.60</td>
</tr>
<tr class="odd">
<td align="left">cosmetics</td>
<td align="left">metrocity</td>
<td align="right">2033</td>
<td align="right">4066</td>
<td align="right">8132</td>
<td align="right">12198</td>
<td align="right">16264</td>
<td align="right">0.61</td>
</tr>
<tr class="even">
<td align="left">cosmetics</td>
<td align="left">metropol avm</td>
<td align="right">2033</td>
<td align="right">4066</td>
<td align="right">8132</td>
<td align="right">12198</td>
<td align="right">16264</td>
<td align="right">0.62</td>
</tr>
<tr class="odd">
<td align="left">cosmetics</td>
<td align="left">viaport outlet</td>
<td align="right">2033</td>
<td align="right">4066</td>
<td align="right">8132</td>
<td align="right">12198</td>
<td align="right">16264</td>
<td align="right">0.62</td>
</tr>
<tr class="even">
<td align="left">cosmetics</td>
<td align="left">zorlu center</td>
<td align="right">2033</td>
<td align="right">4066</td>
<td align="right">8132</td>
<td align="right">12198</td>
<td align="right">16264</td>
<td align="right">0.64</td>
</tr>
<tr class="odd">
<td align="left">food &amp; beverage</td>
<td align="left">cevahir avm</td>
<td align="right">523</td>
<td align="right">1046</td>
<td align="right">1569</td>
<td align="right">2092</td>
<td align="right">523000</td>
<td align="right">8.43</td>
</tr>
<tr class="even">
<td align="left">food &amp; beverage</td>
<td align="left">emaar square mall</td>
<td align="right">523</td>
<td align="right">1046</td>
<td align="right">1569</td>
<td align="right">2092</td>
<td align="right">2615</td>
<td align="right">0.46</td>
</tr>
<tr class="odd">
<td align="left">food &amp; beverage</td>
<td align="left">forum istanbul</td>
<td align="right">523</td>
<td align="right">1046</td>
<td align="right">1569</td>
<td align="right">2092</td>
<td align="right">2615</td>
<td align="right">0.49</td>
</tr>
<tr class="even">
<td align="left">food &amp; beverage</td>
<td align="left">istinye park</td>
<td align="right">523</td>
<td align="right">1046</td>
<td align="right">1569</td>
<td align="right">2092</td>
<td align="right">2615</td>
<td align="right">0.47</td>
</tr>
<tr class="odd">
<td align="left">food &amp; beverage</td>
<td align="left">kanyon</td>
<td align="right">523</td>
<td align="right">1046</td>
<td align="right">1569</td>
<td align="right">2092</td>
<td align="right">2615</td>
<td align="right">0.47</td>
</tr>
<tr class="even">
<td align="left">food &amp; beverage</td>
<td align="left">mall of istanbul</td>
<td align="right">523</td>
<td align="right">1046</td>
<td align="right">1569</td>
<td align="right">2092</td>
<td align="right">2615</td>
<td align="right">0.48</td>
</tr>
<tr class="odd">
<td align="left">food &amp; beverage</td>
<td align="left">metrocity</td>
<td align="right">523</td>
<td align="right">1046</td>
<td align="right">1569</td>
<td align="right">2092</td>
<td align="right">2615</td>
<td align="right">0.47</td>
</tr>
<tr class="even">
<td align="left">food &amp; beverage</td>
<td align="left">metropol avm</td>
<td align="right">523</td>
<td align="right">1046</td>
<td align="right">1569</td>
<td align="right">2092</td>
<td align="right">2615</td>
<td align="right">0.47</td>
</tr>
<tr class="odd">
<td align="left">food &amp; beverage</td>
<td align="left">viaport outlet</td>
<td align="right">523</td>
<td align="right">1046</td>
<td align="right">1569</td>
<td align="right">2092</td>
<td align="right">2615</td>
<td align="right">0.47</td>
</tr>
<tr class="even">
<td align="left">food &amp; beverage</td>
<td align="left">zorlu center</td>
<td align="right">523</td>
<td align="right">1046</td>
<td align="right">1569</td>
<td align="right">2092</td>
<td align="right">2615</td>
<td align="right">0.47</td>
</tr>
<tr class="odd">
<td align="left">shoes</td>
<td align="left">cevahir avm</td>
<td align="right">60017</td>
<td align="right">120034</td>
<td align="right">180051</td>
<td align="right">240068</td>
<td align="right">300085</td>
<td align="right">0.47</td>
</tr>
<tr class="even">
<td align="left">shoes</td>
<td align="left">emaar square mall</td>
<td align="right">60017</td>
<td align="right">120034</td>
<td align="right">180051</td>
<td align="right">240068</td>
<td align="right">300085</td>
<td align="right">0.47</td>
</tr>
<tr class="odd">
<td align="left">shoes</td>
<td align="left">forum istanbul</td>
<td align="right">60017</td>
<td align="right">120034</td>
<td align="right">180051</td>
<td align="right">240068</td>
<td align="right">300085</td>
<td align="right">0.44</td>
</tr>
<tr class="even">
<td align="left">shoes</td>
<td align="left">istinye park</td>
<td align="right">60017</td>
<td align="right">120034</td>
<td align="right">180051</td>
<td align="right">240068</td>
<td align="right">300085</td>
<td align="right">0.47</td>
</tr>
<tr class="odd">
<td align="left">shoes</td>
<td align="left">kanyon</td>
<td align="right">60017</td>
<td align="right">120034</td>
<td align="right">180051</td>
<td align="right">240068</td>
<td align="right">300085</td>
<td align="right">0.47</td>
</tr>
<tr class="even">
<td align="left">shoes</td>
<td align="left">mall of istanbul</td>
<td align="right">60017</td>
<td align="right">120034</td>
<td align="right">180051</td>
<td align="right">240068</td>
<td align="right">300085</td>
<td align="right">0.46</td>
</tr>
<tr class="odd">
<td align="left">shoes</td>
<td align="left">metrocity</td>
<td align="right">60017</td>
<td align="right">120034</td>
<td align="right">180051</td>
<td align="right">240068</td>
<td align="right">300085</td>
<td align="right">0.47</td>
</tr>
<tr class="even">
<td align="left">shoes</td>
<td align="left">metropol avm</td>
<td align="right">60017</td>
<td align="right">120034</td>
<td align="right">180051</td>
<td align="right">240068</td>
<td align="right">300085</td>
<td align="right">0.47</td>
</tr>
<tr class="odd">
<td align="left">shoes</td>
<td align="left">viaport outlet</td>
<td align="right">60017</td>
<td align="right">120034</td>
<td align="right">180051</td>
<td align="right">240068</td>
<td align="right">300085</td>
<td align="right">0.47</td>
</tr>
<tr class="even">
<td align="left">shoes</td>
<td align="left">zorlu center</td>
<td align="right">60017</td>
<td align="right">120034</td>
<td align="right">180051</td>
<td align="right">240068</td>
<td align="right">300085</td>
<td align="right">0.46</td>
</tr>
<tr class="odd">
<td align="left">souvenir</td>
<td align="left">cevahir avm</td>
<td align="right">1173</td>
<td align="right">2346</td>
<td align="right">3519</td>
<td align="right">4692</td>
<td align="right">5865</td>
<td align="right">0.46</td>
</tr>
<tr class="even">
<td align="left">souvenir</td>
<td align="left">emaar square mall</td>
<td align="right">1173</td>
<td align="right">2346</td>
<td align="right">3519</td>
<td align="right">4692</td>
<td align="right">5865</td>
<td align="right">0.49</td>
</tr>
<tr class="odd">
<td align="left">souvenir</td>
<td align="left">forum istanbul</td>
<td align="right">1173</td>
<td align="right">2346</td>
<td align="right">3519</td>
<td align="right">4692</td>
<td align="right">5865</td>
<td align="right">0.47</td>
</tr>
<tr class="even">
<td align="left">souvenir</td>
<td align="left">istinye park</td>
<td align="right">1173</td>
<td align="right">2346</td>
<td align="right">3519</td>
<td align="right">4692</td>
<td align="right">5865</td>
<td align="right">0.48</td>
</tr>
<tr class="odd">
<td align="left">souvenir</td>
<td align="left">kanyon</td>
<td align="right">1173</td>
<td align="right">2346</td>
<td align="right">3519</td>
<td align="right">4692</td>
<td align="right">5865</td>
<td align="right">0.48</td>
</tr>
<tr class="even">
<td align="left">souvenir</td>
<td align="left">mall of istanbul</td>
<td align="right">1173</td>
<td align="right">2346</td>
<td align="right">3519</td>
<td align="right">4692</td>
<td align="right">5865</td>
<td align="right">0.46</td>
</tr>
<tr class="odd">
<td align="left">souvenir</td>
<td align="left">metrocity</td>
<td align="right">1173</td>
<td align="right">2346</td>
<td align="right">3519</td>
<td align="right">4692</td>
<td align="right">5865</td>
<td align="right">0.48</td>
</tr>
<tr class="even">
<td align="left">souvenir</td>
<td align="left">metropol avm</td>
<td align="right">1173</td>
<td align="right">2346</td>
<td align="right">3519</td>
<td align="right">4692</td>
<td align="right">5865</td>
<td align="right">0.47</td>
</tr>
<tr class="odd">
<td align="left">souvenir</td>
<td align="left">viaport outlet</td>
<td align="right">1173</td>
<td align="right">2346</td>
<td align="right">3519</td>
<td align="right">4692</td>
<td align="right">5865</td>
<td align="right">0.49</td>
</tr>
<tr class="even">
<td align="left">souvenir</td>
<td align="left">zorlu center</td>
<td align="right">1173</td>
<td align="right">2346</td>
<td align="right">3519</td>
<td align="right">4692</td>
<td align="right">5865</td>
<td align="right">0.49</td>
</tr>
<tr class="odd">
<td align="left">technology</td>
<td align="left">cevahir avm</td>
<td align="right">1050</td>
<td align="right">2100</td>
<td align="right">3150</td>
<td align="right">4200</td>
<td align="right">5250</td>
<td align="right">0.47</td>
</tr>
<tr class="even">
<td align="left">technology</td>
<td align="left">emaar square mall</td>
<td align="right">1050</td>
<td align="right">2100</td>
<td align="right">3150</td>
<td align="right">4200</td>
<td align="right">5250</td>
<td align="right">0.48</td>
</tr>
<tr class="odd">
<td align="left">technology</td>
<td align="left">forum istanbul</td>
<td align="right">1050</td>
<td align="right">2100</td>
<td align="right">3150</td>
<td align="right">4200</td>
<td align="right">5250</td>
<td align="right">0.49</td>
</tr>
<tr class="even">
<td align="left">technology</td>
<td align="left">istinye park</td>
<td align="right">1050</td>
<td align="right">2100</td>
<td align="right">3150</td>
<td align="right">4200</td>
<td align="right">5250</td>
<td align="right">0.47</td>
</tr>
<tr class="odd">
<td align="left">technology</td>
<td align="left">kanyon</td>
<td align="right">1050</td>
<td align="right">2100</td>
<td align="right">3150</td>
<td align="right">4200</td>
<td align="right">5250</td>
<td align="right">0.47</td>
</tr>
<tr class="even">
<td align="left">technology</td>
<td align="left">mall of istanbul</td>
<td align="right">1050</td>
<td align="right">2100</td>
<td align="right">3150</td>
<td align="right">4200</td>
<td align="right">5250</td>
<td align="right">0.47</td>
</tr>
<tr class="odd">
<td align="left">technology</td>
<td align="left">metrocity</td>
<td align="right">1050</td>
<td align="right">2100</td>
<td align="right">3150</td>
<td align="right">4200</td>
<td align="right">5250</td>
<td align="right">0.48</td>
</tr>
<tr class="even">
<td align="left">technology</td>
<td align="left">metropol avm</td>
<td align="right">1050</td>
<td align="right">2100</td>
<td align="right">3150</td>
<td align="right">4200</td>
<td align="right">5250</td>
<td align="right">0.46</td>
</tr>
<tr class="odd">
<td align="left">technology</td>
<td align="left">viaport outlet</td>
<td align="right">1050</td>
<td align="right">2100</td>
<td align="right">3150</td>
<td align="right">4200</td>
<td align="right">5250</td>
<td align="right">0.47</td>
</tr>
<tr class="even">
<td align="left">technology</td>
<td align="left">zorlu center</td>
<td align="right">3</td>
<td align="right">2100</td>
<td align="right">3150</td>
<td align="right">4200</td>
<td align="right">5250</td>
<td align="right">0.47</td>
</tr>
<tr class="odd">
<td align="left">toys</td>
<td align="left">cevahir avm</td>
<td align="right">1792</td>
<td align="right">3584</td>
<td align="right">7168</td>
<td align="right">10752</td>
<td align="right">14336</td>
<td align="right">0.61</td>
</tr>
<tr class="even">
<td align="left">toys</td>
<td align="left">emaar square mall</td>
<td align="right">1792</td>
<td align="right">3584</td>
<td align="right">7168</td>
<td align="right">10752</td>
<td align="right">14336</td>
<td align="right">0.59</td>
</tr>
<tr class="odd">
<td align="left">toys</td>
<td align="left">forum istanbul</td>
<td align="right">1792</td>
<td align="right">3584</td>
<td align="right">7168</td>
<td align="right">10752</td>
<td align="right">14336</td>
<td align="right">0.63</td>
</tr>
<tr class="even">
<td align="left">toys</td>
<td align="left">istinye park</td>
<td align="right">1792</td>
<td align="right">3584</td>
<td align="right">7168</td>
<td align="right">10752</td>
<td align="right">14336</td>
<td align="right">0.61</td>
</tr>
<tr class="odd">
<td align="left">toys</td>
<td align="left">kanyon</td>
<td align="right">1792</td>
<td align="right">3584</td>
<td align="right">7168</td>
<td align="right">10752</td>
<td align="right">14336</td>
<td align="right">0.62</td>
</tr>
<tr class="even">
<td align="left">toys</td>
<td align="left">mall of istanbul</td>
<td align="right">1792</td>
<td align="right">3584</td>
<td align="right">7168</td>
<td align="right">10752</td>
<td align="right">14336</td>
<td align="right">0.60</td>
</tr>
<tr class="odd">
<td align="left">toys</td>
<td align="left">metrocity</td>
<td align="right">1792</td>
<td align="right">3584</td>
<td align="right">7168</td>
<td align="right">10752</td>
<td align="right">14336</td>
<td align="right">0.59</td>
</tr>
<tr class="even">
<td align="left">toys</td>
<td align="left">metropol avm</td>
<td align="right">1792</td>
<td align="right">3584</td>
<td align="right">7168</td>
<td align="right">10752</td>
<td align="right">14336</td>
<td align="right">0.60</td>
</tr>
<tr class="odd">
<td align="left">toys</td>
<td align="left">viaport outlet</td>
<td align="right">1792</td>
<td align="right">3584</td>
<td align="right">7168</td>
<td align="right">10752</td>
<td align="right">14336</td>
<td align="right">0.62</td>
</tr>
<tr class="even">
<td align="left">toys</td>
<td align="left">zorlu center</td>
<td align="right">1792</td>
<td align="right">3584</td>
<td align="right">7168</td>
<td align="right">10752</td>
<td align="right">14336</td>
<td align="right">0.58</td>
</tr>
</tbody>
</table>
<p>Para facilitar la presentación de las cifras, el precio se reescaló a miles de unidades monetarias (price := price/1,000). Todas las imputaciones y transformaciones logarítmicas se realizaron sobre esta escala; los precios imputados resultan, por tanto, en miles.</p>
<div class="figure"><span style="display:block;" id="fig:fig-precio-categorias"></span>
<img src="Informe-descriptivo_files/figure-html/fig-precio-categorias-1.png" alt="Precio (liras turcas), en unidades de  mil, por Categoría del producto." width="672" />
<p class="caption">
Figure 5.3: Precio (liras turcas), en unidades de mil, por Categoría del producto.
</p>
</div>
<table>
<caption><span id="tab:tabla-precio-categoria">Table 5.3: </span>Estadísticas del Precio (liras turcas), en unidades de mil, sin 3 atípicos. En la tabla se presentan el número de registros (n), el primer cuartil (Q1),
la mediana (Q2), el tercer cuartil (Q3), el valor mínimo (Min),
el valor máximo (Max), así como la cantidad de atípicos inferiores (Atm)
y superiores (AtM).</caption>
<colgroup>
<col width="19%" />
<col width="7%" />
<col width="14%" />
<col width="8%" />
<col width="9%" />
<col width="9%" />
<col width="9%" />
<col width="10%" />
<col width="4%" />
<col width="4%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">category</th>
<th align="right">n</th>
<th align="right">NA en price</th>
<th align="right">Min</th>
<th align="right">Q1</th>
<th align="right">Q2</th>
<th align="right">Q3</th>
<th align="right">Max</th>
<th align="right">Atm</th>
<th align="right">AtM</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">books</td>
<td align="right">4980</td>
<td align="right">1</td>
<td align="right">0.303</td>
<td align="right">0.606</td>
<td align="right">1.515</td>
<td align="right">4.545</td>
<td align="right">7575.000</td>
<td align="right">0</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="left">clothing</td>
<td align="right">34486</td>
<td align="right">5</td>
<td align="right">0.001</td>
<td align="right">30.008</td>
<td align="right">60.016</td>
<td align="right">90.024</td>
<td align="right">120.032</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">cosmetics</td>
<td align="right">15096</td>
<td align="right">6</td>
<td align="right">2.033</td>
<td align="right">4.066</td>
<td align="right">8.132</td>
<td align="right">12.198</td>
<td align="right">16.264</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">food &amp; beverage</td>
<td align="right">14775</td>
<td align="right">3</td>
<td align="right">0.523</td>
<td align="right">1.046</td>
<td align="right">1.569</td>
<td align="right">2.092</td>
<td align="right">523.000</td>
<td align="right">0</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="left">shoes</td>
<td align="right">10032</td>
<td align="right">2</td>
<td align="right">60.017</td>
<td align="right">120.034</td>
<td align="right">180.051</td>
<td align="right">240.068</td>
<td align="right">300.085</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">souvenir</td>
<td align="right">4999</td>
<td align="right">1</td>
<td align="right">1.173</td>
<td align="right">2.346</td>
<td align="right">3.519</td>
<td align="right">4.692</td>
<td align="right">5.865</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">technology</td>
<td align="right">4995</td>
<td align="right">2</td>
<td align="right">0.003</td>
<td align="right">2.100</td>
<td align="right">3.150</td>
<td align="right">4.200</td>
<td align="right">5.250</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">toys</td>
<td align="right">10087</td>
<td align="right">2</td>
<td align="right">1.792</td>
<td align="right">3.584</td>
<td align="right">7.168</td>
<td align="right">10.752</td>
<td align="right">14.336</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p>La Figura <a href="procesamiento.html#fig:fig-precio-categorias">5.3</a> indica que, en la variable <em>Precio</em>, se detectó al menos un valor atípico en la categoría <code>books, food and beverage</code>. La Tabla <a href="procesamiento.html#tab:tabla-precio-categoria">5.3</a> presenta las estadísticas de la variable <em>Precio</em> para cada categoría de productos. Se observa que en las categorías <code>books</code> y <code>food and beverage</code> el precio de un producto es significativamente superior al de los demás. Asimismo, se identificó un valor atípico entre los nueve datos faltantes (<code>NA</code>) de los productos sin categoría conocida.</p>
<p>Los valores atípicos de 7,575,000 y 523,000 liras turcas, correspondientes a las categorías <code>books</code> y <code>food and beverage</code>, representan precios unitarios muy altos para sus respectivas categorías. Por ello, se consideran valores inconsistentes. Estos tres datos atípicos serán tratados como datos faltantes (<code>NA</code>) en el resto del análisis. Posteriormente, se observa en la Figura <a href="procesamiento.html#fig:fig-precio-categoria-sin-atipicos">5.4</a> que la variable <em>Precio</em> ya no presenta estos valores inconsistentes.</p>
<div class="figure"><span style="display:block;" id="fig:fig-precio-categoria-sin-atipicos"></span>
<img src="Informe-descriptivo_files/figure-html/fig-precio-categoria-sin-atipicos-1.png" alt="Precio (liras turcas), en unidades de mil,  por categoría del producto sin atípicos." width="672" />
<p class="caption">
Figure 5.4: Precio (liras turcas), en unidades de mil, por categoría del producto sin atípicos.
</p>
</div>
<p>La Tabla <a href="procesamiento.html#tab:tabla-precio-categoria-sin-atipicos2">5.4</a> muestra las estadísticas de la variable <em>Precio</em> excluyendo las tres inconsistencias identificadas por valores atípicos. Se ha observado que, en las categorías <code>clothing</code> y <code>technology</code>, los valores de 1 y 3 liras turcas, respectivamente, no son plausibles en centros comerciales de ropa y tecnología nueva. Por ello, dichos valores han sido clasificados como inconsistentes y, en lo sucesivo, se tratarán como datos faltantes.</p>
<p>Adicionalmente, se ha determinado que el valor de 7,575 liras turcas asignado a la categoría de <code>books</code> solo podría corresponder a ediciones de lujo, las cuales no están contempladas en los centros comerciales de la muestra. La Tabla <a href="procesamiento.html#tab:tabla-precio-categoria-sin-atipicos-sin-inconsistencias">5.5</a> presenta las estadísticas de la variable <em>Precio</em> luego de reemplazar estas inconsistencias por <code>NA</code>. Asimismo, se evidencia que el valor de 2 liras turcas para la categoría <code>clothing</code> debe ser considerado <code>NA</code>.</p>
<p>La Tabla <a href="procesamiento.html#tab:tabla-precio-categoria-sin-atipicos-sin-inconsistencias2">5.6</a> expone las estadísticas del precio por categoría tras el tratamiento de las inconsistencias como datos faltantes. Se ha determinado que los siguientes rangos de precios en liras turcas son plausibles en los diez centros comerciales de la muestra:</p>
<ul>
<li><p><code>books</code>: entre 303 y 4,545</p></li>
<li><p><code>clothing</code>: entre 15,004 y 120,032</p></li>
<li><p><code>cosmetics</code>: entre 2,033 y 16,264</p></li>
<li><p><code>food and Beverage</code>: entre 523 y 2,615</p></li>
<li><p><code>shoes</code>: entre 60,017 y 300,085</p></li>
<li><p><code>souvenir</code>: entre 1,173 y 5,865</p></li>
<li><p><code>technology</code>: entre 1,050 y 5,250</p></li>
<li><p><code>toys</code>: entre 1,792 y 14,336</p></li>
</ul>
<table>
<caption><span id="tab:tabla-precio-categoria-sin-atipicos2">Table 5.4: </span>Estadísticas del Precio (liras turcas), en unidades de mil, sin 3 atípicos. En la tabla se presentan el número de registros (n), el primer cuartil (Q1),
la mediana (Q2), el tercer cuartil (Q3), el valor mínimo (Min),
el valor máximo (Max), así como la cantidad de atípicos inferiores (Atm)
y superiores (AtM).</caption>
<colgroup>
<col width="19%" />
<col width="7%" />
<col width="14%" />
<col width="8%" />
<col width="9%" />
<col width="9%" />
<col width="9%" />
<col width="9%" />
<col width="4%" />
<col width="4%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">category</th>
<th align="right">n</th>
<th align="right">NA en price</th>
<th align="right">Min</th>
<th align="right">Q1</th>
<th align="right">Q2</th>
<th align="right">Q3</th>
<th align="right">Max</th>
<th align="right">Atm</th>
<th align="right">AtM</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">books</td>
<td align="right">4980</td>
<td align="right">2</td>
<td align="right">0.303</td>
<td align="right">0.606</td>
<td align="right">1.515</td>
<td align="right">4.545</td>
<td align="right">7.575</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">clothing</td>
<td align="right">34486</td>
<td align="right">5</td>
<td align="right">0.001</td>
<td align="right">30.008</td>
<td align="right">60.016</td>
<td align="right">90.024</td>
<td align="right">120.032</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">cosmetics</td>
<td align="right">15096</td>
<td align="right">6</td>
<td align="right">2.033</td>
<td align="right">4.066</td>
<td align="right">8.132</td>
<td align="right">12.198</td>
<td align="right">16.264</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">food &amp; beverage</td>
<td align="right">14775</td>
<td align="right">4</td>
<td align="right">0.523</td>
<td align="right">1.046</td>
<td align="right">1.569</td>
<td align="right">2.092</td>
<td align="right">2.615</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">shoes</td>
<td align="right">10032</td>
<td align="right">2</td>
<td align="right">60.017</td>
<td align="right">120.034</td>
<td align="right">180.051</td>
<td align="right">240.068</td>
<td align="right">300.085</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">souvenir</td>
<td align="right">4999</td>
<td align="right">1</td>
<td align="right">1.173</td>
<td align="right">2.346</td>
<td align="right">3.519</td>
<td align="right">4.692</td>
<td align="right">5.865</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">technology</td>
<td align="right">4995</td>
<td align="right">2</td>
<td align="right">0.003</td>
<td align="right">2.100</td>
<td align="right">3.150</td>
<td align="right">4.200</td>
<td align="right">5.250</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">toys</td>
<td align="right">10087</td>
<td align="right">2</td>
<td align="right">1.792</td>
<td align="right">3.584</td>
<td align="right">7.168</td>
<td align="right">10.752</td>
<td align="right">14.336</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<table>
<caption><span id="tab:tabla-precio-categoria-sin-atipicos-sin-inconsistencias">Table 5.5: </span>Estadísticas del Precio (liras turcas), en unidades de mil, sin inconsistencias de clothing y technology. En la tabla se presentan el número de registros (n), el primer cuartil (Q1),
la mediana (Q2), el tercer cuartil (Q3), el valor mínimo (Min),
el valor máximo (Max), así como la cantidad de atípicos inferiores (Atm)
y superiores (AtM).</caption>
<colgroup>
<col width="19%" />
<col width="7%" />
<col width="14%" />
<col width="8%" />
<col width="9%" />
<col width="9%" />
<col width="9%" />
<col width="9%" />
<col width="4%" />
<col width="4%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">category</th>
<th align="right">n</th>
<th align="right">NA en price</th>
<th align="right">Min</th>
<th align="right">Q1</th>
<th align="right">Q2</th>
<th align="right">Q3</th>
<th align="right">Max</th>
<th align="right">Atm</th>
<th align="right">AtM</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">books</td>
<td align="right">4980</td>
<td align="right">2</td>
<td align="right">0.303</td>
<td align="right">0.606</td>
<td align="right">1.515</td>
<td align="right">4.545</td>
<td align="right">7.575</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">clothing</td>
<td align="right">34486</td>
<td align="right">5</td>
<td align="right">0.001</td>
<td align="right">30.008</td>
<td align="right">60.016</td>
<td align="right">90.024</td>
<td align="right">120.032</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">cosmetics</td>
<td align="right">15096</td>
<td align="right">6</td>
<td align="right">2.033</td>
<td align="right">4.066</td>
<td align="right">8.132</td>
<td align="right">12.198</td>
<td align="right">16.264</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">food &amp; beverage</td>
<td align="right">14775</td>
<td align="right">4</td>
<td align="right">0.523</td>
<td align="right">1.046</td>
<td align="right">1.569</td>
<td align="right">2.092</td>
<td align="right">2.615</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">shoes</td>
<td align="right">10032</td>
<td align="right">2</td>
<td align="right">60.017</td>
<td align="right">120.034</td>
<td align="right">180.051</td>
<td align="right">240.068</td>
<td align="right">300.085</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">souvenir</td>
<td align="right">4999</td>
<td align="right">1</td>
<td align="right">1.173</td>
<td align="right">2.346</td>
<td align="right">3.519</td>
<td align="right">4.692</td>
<td align="right">5.865</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">technology</td>
<td align="right">4995</td>
<td align="right">2</td>
<td align="right">0.003</td>
<td align="right">2.100</td>
<td align="right">3.150</td>
<td align="right">4.200</td>
<td align="right">5.250</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">toys</td>
<td align="right">10087</td>
<td align="right">2</td>
<td align="right">1.792</td>
<td align="right">3.584</td>
<td align="right">7.168</td>
<td align="right">10.752</td>
<td align="right">14.336</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<table>
<caption><span id="tab:tabla-precio-categoria-sin-atipicos-sin-inconsistencias2">Table 5.6: </span>Estadísticas del Precio (liras turcas), en unidades de mil, sin inconsistencias de clothing y technology. En la tabla se presentan el número de registros (n), el primer cuartil (Q1),
la mediana (Q2), el tercer cuartil (Q3), el valor mínimo (Min),
el valor máximo (Max), así como la cantidad de atípicos inferiores (Atm)
y superiores (AtM).</caption>
<colgroup>
<col width="19%" />
<col width="7%" />
<col width="14%" />
<col width="8%" />
<col width="9%" />
<col width="9%" />
<col width="9%" />
<col width="9%" />
<col width="4%" />
<col width="4%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">category</th>
<th align="right">n</th>
<th align="right">NA en price</th>
<th align="right">Min</th>
<th align="right">Q1</th>
<th align="right">Q2</th>
<th align="right">Q3</th>
<th align="right">Max</th>
<th align="right">Atm</th>
<th align="right">AtM</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">books</td>
<td align="right">4980</td>
<td align="right">2</td>
<td align="right">0.303</td>
<td align="right">0.606</td>
<td align="right">1.515</td>
<td align="right">4.545</td>
<td align="right">7.575</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">clothing</td>
<td align="right">34486</td>
<td align="right">5</td>
<td align="right">0.001</td>
<td align="right">30.008</td>
<td align="right">60.016</td>
<td align="right">90.024</td>
<td align="right">120.032</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">cosmetics</td>
<td align="right">15096</td>
<td align="right">6</td>
<td align="right">2.033</td>
<td align="right">4.066</td>
<td align="right">8.132</td>
<td align="right">12.198</td>
<td align="right">16.264</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">food &amp; beverage</td>
<td align="right">14775</td>
<td align="right">4</td>
<td align="right">0.523</td>
<td align="right">1.046</td>
<td align="right">1.569</td>
<td align="right">2.092</td>
<td align="right">2.615</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">shoes</td>
<td align="right">10032</td>
<td align="right">2</td>
<td align="right">60.017</td>
<td align="right">120.034</td>
<td align="right">180.051</td>
<td align="right">240.068</td>
<td align="right">300.085</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">souvenir</td>
<td align="right">4999</td>
<td align="right">1</td>
<td align="right">1.173</td>
<td align="right">2.346</td>
<td align="right">3.519</td>
<td align="right">4.692</td>
<td align="right">5.865</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">technology</td>
<td align="right">4995</td>
<td align="right">2</td>
<td align="right">0.003</td>
<td align="right">2.100</td>
<td align="right">3.150</td>
<td align="right">4.200</td>
<td align="right">5.250</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">toys</td>
<td align="right">10087</td>
<td align="right">2</td>
<td align="right">1.792</td>
<td align="right">3.584</td>
<td align="right">7.168</td>
<td align="right">10.752</td>
<td align="right">14.336</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
</div>
<div id="cantidad-de-productos" class="section level4 hasAnchor" number="5.1.2.4">
<h4><span class="header-section-number">5.1.2.4</span> Cantidad de productos<a href="procesamiento.html#cantidad-de-productos" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Por último, la Tabla <a href="procesamiento.html#tab:tabla-cantidad-categoria">5.7</a> presenta las estadísticas descriptivas del número de artículos por categoría. Se observa que la cantidad de ítems por transacción oscila entre 1 y 5, sin valores atípicos ni inconsistencias que requieran corrección.</p>
<table>
<caption><span id="tab:tabla-cantidad-categoria">Table 5.7: </span>Estadísticas de Cantidad de productos. En la tabla se presentan el número de registros (n), el primer cuartil (Q1),
la mediana (Q2), el tercer cuartil (Q3), el valor mínimo (Min),
el valor máximo (Max), así como la cantidad de atípicos inferiores (Atm)
y superiores (AtM).</caption>
<thead>
<tr class="header">
<th align="left">category</th>
<th align="right">n</th>
<th align="right">NA en price</th>
<th align="right">min</th>
<th align="right">Q1</th>
<th align="right">Q2</th>
<th align="right">Q3</th>
<th align="right">Max</th>
<th align="right">Atm</th>
<th align="right">AtM</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">books</td>
<td align="right">4980</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">3</td>
<td align="right">4</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">clothing</td>
<td align="right">34486</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">3</td>
<td align="right">4</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">cosmetics</td>
<td align="right">15096</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">3</td>
<td align="right">4</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">food &amp; beverage</td>
<td align="right">14775</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">3</td>
<td align="right">4</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">shoes</td>
<td align="right">10032</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">3</td>
<td align="right">4</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">souvenir</td>
<td align="right">4999</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">3</td>
<td align="right">4</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">technology</td>
<td align="right">4995</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">3</td>
<td align="right">4</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">toys</td>
<td align="right">10087</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">3</td>
<td align="right">4</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<hr />
</div>
</div>
</div>
<div id="análisis-de-datos-atípicos" class="section level2 hasAnchor" number="5.2">
<h2><span class="header-section-number">5.2</span> Análisis de datos atípicos<a href="procesamiento.html#análisis-de-datos-atípicos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Según los hallazgos, los valores atípicos detectados en la variable <em>Precio</em> —evaluada por categoría— corresponden a inconsistencias que se han recodificado como valores faltantes (<code>NA</code>), los que posteriormente serán imputados. Por su parte, las variables <em>Edad</em> y <em>Cantidad</em> de artículos no presentan outliers. En consecuencia, de cara al análisis posterior se asume que las variables cuantitativas están libres de datos atípicos.</p>
<hr />
</div>
<div id="identificación-de-datos-faltantes" class="section level2 hasAnchor" number="5.3">
<h2><span class="header-section-number">5.3</span> Identificación de datos faltantes<a href="procesamiento.html#identificación-de-datos-faltantes" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>La Figura <a href="procesamiento.html#fig:fig-datos-faltantes">5.5</a> muestra que las variables <em>Precio</em>, <em>Sexo</em> y <em>Edad</em> presentan el mayor porcentaje de datos faltantes, seguidas de <em>Centro comercial</em> y <em>Método de pago</em>. Asimismo, evidencia que el porcentaje más alto de datos faltantes no supera el 1.06%.</p>
<p>Adicionalmente, la Figura <a href="procesamiento.html#fig:fig-datos-faltantes">5.5</a> indica que 99,369 de los registros no presenta datos faltantes (combinación 1), mientras que el 24 de registros presenta valores faltantes en <em>Precio</em> (combinación 2). Además, se identificaron el 19 de registros con datos faltantes en <em>Edad</em> (combinación 3) y otro 19 en <em>Sexo</em> (combinación 4). De igual forma, se detectó que 11 de los registros tienen datos faltantes en <em>Centros comerciales</em> (combinación 5) y 8 en <em>Método de pago</em> (combinación 6). La Figura <a href="procesamiento.html#fig:fig-datos-faltantes">5.5</a> se presenta un resumen de las variables ordenadas según el número de datos faltantes.</p>
<div class="figure"><span style="display:block;" id="fig:fig-datos-faltantes"></span>
<img src="Informe-descriptivo_files/figure-html/fig-datos-faltantes-1.png" alt="Porcentaje de datos faltantes por variables y combinaciones de faltantes por variables." width="960" />
<p class="caption">
Figure 5.5: Porcentaje de datos faltantes por variables y combinaciones de faltantes por variables.
</p>
</div>
<pre><code>## 
##  Variables sorted by number of missings: 
##        Variable Count
##           price    24
##          gender    19
##             age    19
##   shopping_mall    11
##  payment_method     8
##      invoice_no     0
##     customer_id     0
##        category     0
##        quantity     0
##    invoice_date     0</code></pre>
<p>Para evaluar formalmente si las ausencias se distribuyen de manera completamente aleatoria (MCAR), se aplicó la prueba de Little (implementada en <code>naniar::mcar_test()</code>) a las variables cuantitativas (<em>Edad</em>, <em>Cantidad</em>, <em>Precio</em>), cuya hipótesis nula establece que los datos faltantes se distribuyen de forma aleatoria. Dado el gran tamaño de la base de datos (99,450 registros), se estableció un nivel de significancia muy estricto (0.001).</p>
<p>El <span class="math inline">\(valor-p\)</span> obtenido fue igual a 0.207492, lo que lleva a no rechazar la hipótesis nula con una significancia del 1%. Esto indica que no existe evidencia suficiente para descartar que los datos faltantes sean completamente aleatorios.</p>
<pre><code>## [1] 0.207492</code></pre>
<div class="figure"><span style="display:block;" id="fig:figNormMCAR"></span>
<img src="Informe-descriptivo_files/figure-html/figNormMCAR-1.png" alt=" Q-Q de age, de quantity, de price. Además, densidad de age, de quantity, de price" width="672" />
<p class="caption">
Figure 5.6:  Q-Q de age, de quantity, de price. Además, densidad de age, de quantity, de price
</p>
</div>
<p>Según la Figura <a href="procesamiento.html#fig:figNormMCAR">5.6</a>, las variables cuantitativas no cumplen el supuesto de la normalidad debido principalmente a la marcada discrecionalidad de <em>Cantidad</em> y a la fuerte asimetría observada en <em>Precio</em>. Este incumplimiento de los supuestos necesarios pone en entredicho la fiabilidad del test MCAR (basado en el método de Little), que indicó que los datos se distribuyen de forma completamente aleatoria.</p>
<p>El objetivo del siguiente análisis es evaluar el mecanismo de ausencia de datos en la variable <em>Precio</em>. Para ello, se creó una variable indicadora que refleja si el dato de <em>Precio</em> está ausente (1) o presente (0). Posteriormente, se ajustó un modelo de regresión logística utilizando como predictores las variables <em>Edad</em>, <em>Cantidad</em>, <em>Sexo</em>, <em>Método de pago</em> y <em>Categoría</em>.</p>
<p>El modelo permite determinar si la probabilidad de tener un dato faltante en <em>Precio</em> está asociada a alguna de estas variables, lo que ayudaría a descartar la hipótesis de que los datos faltantes se distribuyen de forma completamente aleatoria (MCAR).</p>
<pre><code>## 
## Call:
## glm(formula = miss_price ~ age + quantity + factor(gender) + 
##     factor(category) + factor(payment_method), family = binomial, 
##     data = datos_mod4)
## 
## Coefficients:
##                                    Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)                       -6.924640   1.037413  -6.675 2.47e-11 ***
## age                                0.002582   0.013644   0.189   0.8499    
## quantity                          -0.352605   0.155978  -2.261   0.0238 *  
## factor(gender)male                -0.117759   0.421729  -0.279   0.7801    
## factor(category)clothing          -1.018422   0.836850  -1.217   0.2236    
## factor(category)cosmetics         -0.010011   0.816751  -0.012   0.9902    
## factor(category)food &amp; beverage   -0.394462   0.866261  -0.455   0.6488    
## factor(category)shoes             -0.696221   1.000193  -0.696   0.4864    
## factor(category)souvenir          -0.706553   1.224956  -0.577   0.5641    
## factor(category)technology        -0.003626   1.000280  -0.004   0.9971    
## factor(category)toys              -0.703219   1.000221  -0.703   0.4820    
## factor(payment_method)credit card -0.360599   0.507573  -0.710   0.4774    
## factor(payment_method)debit card   0.341974   0.483591   0.707   0.4795    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 447.78  on 99403  degrees of freedom
## Residual deviance: 436.57  on 99391  degrees of freedom
##   (46 observations deleted due to missingness)
## AIC: 462.57
## 
## Number of Fisher Scoring iterations: 11</code></pre>
<p>De acuerdo con el modelo de regresión logística, la variable <em>Cantidad</em> se asocia de forma significativa con la probabilidad de ausencia de <em>Precio</em> (<span class="math inline">\(valor-p = 0.0238\)</span>) al nivel de significancia del 3%, mientras que <em>Edad</em>, <em>Método de pago</em>, <em>Categoría</em> y <em>Sexo</em> no resultan predictores relevantes de dicha ausencia. Este hallazgo descarta la hipótesis de “datos faltantes completamente al azar” (<em>MCAR</em>), aunque el gran tamaño muestral (&gt; 99 000 observaciones) incrementa la potencia estadística y aconseja adoptar un umbral de significancia más estricto. Para minimizar posibles sesgos, la imputación de <em>Precio</em> se realizará mediante un enfoque estratificado que contemple tanto los valores de <em>Cantidad</em> como la <em>Categoría</em> del producto.</p>
<p>El objetivo del siguiente análisis es evaluar el mecanismo de ausencia de datos en la variable <em>Edad</em>. Para ello, se creó una variable indicadora que toma valor 1 cuando <em>Edad</em> está ausente y 0 cuando está presente. A continuación, se ajustó un modelo de regresión logística utilizando como predictores <em>Precio</em>, <em>Cantidad</em>, <em>Sexo</em>, <em>Método de pago</em> y <em>Categoría</em>.</p>
<pre><code>## 
## Call:
## glm(formula = miss_age ~ price + quantity + factor(gender) + 
##     factor(category) + factor(payment_method), family = binomial, 
##     data = datos_mod4)
## 
## Coefficients:
##                                     Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept)                       -2.399e+01  1.117e+03  -0.021    0.983
## price                             -2.033e-03  7.668e-03  -0.265    0.791
## quantity                           7.893e-02  1.603e-01   0.492    0.622
## factor(gender)male                -3.700e-01  4.936e-01  -0.750    0.454
## factor(category)clothing           1.561e+01  1.117e+03   0.014    0.989
## factor(category)cosmetics          1.462e+01  1.117e+03   0.013    0.990
## factor(category)food &amp; beverage    1.394e+01  1.117e+03   0.012    0.990
## factor(category)shoes              3.587e-01  1.367e+03   0.000    1.000
## factor(category)souvenir           1.572e+01  1.117e+03   0.014    0.989
## factor(category)technology         1.503e+01  1.117e+03   0.013    0.989
## factor(category)toys               1.503e+01  1.117e+03   0.013    0.989
## factor(payment_method)credit card  3.973e-01  5.564e-01   0.714    0.475
## factor(payment_method)debit card   7.920e-01  5.775e-01   1.372    0.170
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 363.37  on 99398  degrees of freedom
## Residual deviance: 349.69  on 99386  degrees of freedom
##   (51 observations deleted due to missingness)
## AIC: 375.69
## 
## Number of Fisher Scoring iterations: 22</code></pre>
<p>El modelo no evidencia ninguna asociación estadísticamente significativa entre la ausencia de <em>Edad</em> y las variables consideradas; el valor mínimo de <span class="math inline">\(valor\text{-}p\)</span> fue 0.475. Por tanto, al nivel de significancia del 5 %, no hay evidencia de que la falta de <em>Edad</em> dependa de estos predictores, lo que respalda la hipótesis de ausencia completamente al azar (MCAR) para esta variable.</p>
<p>En la tabla de contingencia siguiente que relaciona la presencia y ausencia de datos en <em>Método de pago</em> con las distintas categorías de productos, se observa que casi todos los registros se concentran en la fila 0 (datos presentes), mientras que la fila 1 (datos faltantes) muestra recuentos extremadamente bajos. Al aplicar el test test Fisher’s Exact, se obtuvo un <span class="math inline">\(valor-p\)</span> de 0.2013, lo que lleva a no rechazar la hipótesis nula de independencia con una significancia del 5%. En otras palabras, no se encontró evidencia estadística suficiente para concluir que exista una asociación significativa entre la categoría del producto y la presencia de datos faltantes en <em>Método de pago</em>.</p>
<pre><code>##    
##     books clothing cosmetics food &amp; beverage shoes souvenir technology  toys
##   0  4978    34483     15095           14775 10032     4999       4994 10086
##   1     2        3         1               0     0        0          1     1</code></pre>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  tabla_contingencia
## p-value = 0.2013
## alternative hypothesis: two.sided</code></pre>
<p>En la tabla de contingencia siguiente que relaciona la ausencia de <em>Método de pago</em> con <em>Sexo</em>, se observa que la gran mayoría de los registros tienen datos presentes (fila 0), con 59,461 registros para ‘female’ y 39,962 para ‘male’, mientras que en la fila de datos faltantes (fila 1) apenas hay 6 registros para ‘female’ y 2 para ‘male’.</p>
<p>Al aplicar el test Fisher’s Exact, se obtuvo un <span class="math inline">\(valor-p\)</span> de 0.488. Este resultado indica que no se rechaza la hipótesis nula de independencia con una significancia del 5%, lo que significa que no se encontró evidencia estadística significativa para afirmar que exista una asociación entre el <em>Sexo</em> y la ausencia de <em>Método de pago</em>.</p>
<pre><code>##    
##     female  male
##   0  59461 39962
##   1      6     2</code></pre>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  tabla_contingencia
## p-value = 0.488
## alternative hypothesis: true odds ratio is not equal to 1
## 95 percent confidence interval:
##  0.04895577 2.77392230
## sample estimates:
## odds ratio 
##  0.4959847</code></pre>
</div>
<div id="imputación-de-datos-faltantes" class="section level2 hasAnchor" number="5.4">
<h2><span class="header-section-number">5.4</span> Imputación de datos faltantes<a href="procesamiento.html#imputación-de-datos-faltantes" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="imputación-del-precio-price" class="section level3 hasAnchor" number="5.4.1">
<h3><span class="header-section-number">5.4.1</span> Imputación del Precio (price)<a href="procesamiento.html#imputación-del-precio-price" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>De acuerdo con la Figura <a href="procesamiento.html#fig:figinfprecio">5.7</a> y los resultados de la Tabla <a href="procesamiento.html#tab:tabla-resultadomalls0">5.8</a> la distribución del precio por categoría y centro comercial es muy similar. Teniendo en cuenta los resultados de la sección anterior, la estrategia consiste en imputar los valores faltantes de la variable <em>Precio</em> utilizando la información de la <em>Cantidad</em> y <em>Categoria</em>.</p>
<div class="figure"><span style="display:block;" id="fig:figinfprecio"></span>
<img src="Informe-descriptivo_files/figure-html/figinfprecio-1.png" alt="Distribución del precio  (unidades de 10 mil) por producto y centro comercial." width="672" />
<p class="caption">
Figure 5.7: Distribución del precio (unidades de 10 mil) por producto y centro comercial.
</p>
</div>
<table>
<caption><span id="tab:tabla-resultadomalls0">Table 5.8: </span>Resumen del precio por categoría y centro comercial. Q1: primer cuartil; Mediana (Q2); Q3: tercer cuartil; Min: mínimo; Máx.: máximo; CV: coeficiente de variación.</caption>
<colgroup>
<col width="21%" />
<col width="24%" />
<col width="9%" />
<col width="9%" />
<col width="10%" />
<col width="10%" />
<col width="6%" />
<col width="6%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Categoría</th>
<th align="left">Centro comercial</th>
<th align="right">Mínimo</th>
<th align="right">Q1</th>
<th align="right">Mediana</th>
<th align="right">Q3</th>
<th align="right">Máx.</th>
<th align="right">CV</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">books</td>
<td align="left">cevahir avm</td>
<td align="right">0.30</td>
<td align="right">0.61</td>
<td align="right">2</td>
<td align="right">4.545</td>
<td align="right">8</td>
<td align="right">0.94</td>
</tr>
<tr class="even">
<td align="left">books</td>
<td align="left">emaar square mall</td>
<td align="right">0.30</td>
<td align="right">0.61</td>
<td align="right">2</td>
<td align="right">4.545</td>
<td align="right">8</td>
<td align="right">0.90</td>
</tr>
<tr class="odd">
<td align="left">books</td>
<td align="left">forum istanbul</td>
<td align="right">0.30</td>
<td align="right">0.61</td>
<td align="right">2</td>
<td align="right">4.545</td>
<td align="right">8</td>
<td align="right">0.98</td>
</tr>
<tr class="even">
<td align="left">books</td>
<td align="left">istinye park</td>
<td align="right">0.30</td>
<td align="right">0.61</td>
<td align="right">2</td>
<td align="right">4.545</td>
<td align="right">8</td>
<td align="right">0.96</td>
</tr>
<tr class="odd">
<td align="left">books</td>
<td align="left">kanyon</td>
<td align="right">0.30</td>
<td align="right">0.61</td>
<td align="right">2</td>
<td align="right">4.545</td>
<td align="right">8</td>
<td align="right">0.94</td>
</tr>
<tr class="even">
<td align="left">books</td>
<td align="left">mall of istanbul</td>
<td align="right">0.30</td>
<td align="right">0.61</td>
<td align="right">2</td>
<td align="right">4.545</td>
<td align="right">8</td>
<td align="right">0.94</td>
</tr>
<tr class="odd">
<td align="left">books</td>
<td align="left">metrocity</td>
<td align="right">0.30</td>
<td align="right">0.61</td>
<td align="right">2</td>
<td align="right">4.545</td>
<td align="right">8</td>
<td align="right">0.96</td>
</tr>
<tr class="even">
<td align="left">books</td>
<td align="left">metropol avm</td>
<td align="right">0.30</td>
<td align="right">0.61</td>
<td align="right">2</td>
<td align="right">4.545</td>
<td align="right">8</td>
<td align="right">0.94</td>
</tr>
<tr class="odd">
<td align="left">books</td>
<td align="left">viaport outlet</td>
<td align="right">0.30</td>
<td align="right">0.61</td>
<td align="right">2</td>
<td align="right">4.545</td>
<td align="right">8</td>
<td align="right">0.95</td>
</tr>
<tr class="even">
<td align="left">books</td>
<td align="left">zorlu center</td>
<td align="right">0.30</td>
<td align="right">0.61</td>
<td align="right">2</td>
<td align="right">4.545</td>
<td align="right">8</td>
<td align="right">0.94</td>
</tr>
<tr class="odd">
<td align="left">clothing</td>
<td align="left">cevahir avm</td>
<td align="right">0.00</td>
<td align="right">30.01</td>
<td align="right">60</td>
<td align="right">90.024</td>
<td align="right">120</td>
<td align="right">0.62</td>
</tr>
<tr class="even">
<td align="left">clothing</td>
<td align="left">emaar square mall</td>
<td align="right">15.00</td>
<td align="right">30.01</td>
<td align="right">60</td>
<td align="right">90.024</td>
<td align="right">120</td>
<td align="right">0.61</td>
</tr>
<tr class="odd">
<td align="left">clothing</td>
<td align="left">forum istanbul</td>
<td align="right">15.00</td>
<td align="right">30.01</td>
<td align="right">60</td>
<td align="right">90.024</td>
<td align="right">120</td>
<td align="right">0.61</td>
</tr>
<tr class="even">
<td align="left">clothing</td>
<td align="left">istinye park</td>
<td align="right">15.00</td>
<td align="right">30.01</td>
<td align="right">60</td>
<td align="right">90.024</td>
<td align="right">120</td>
<td align="right">0.61</td>
</tr>
<tr class="odd">
<td align="left">clothing</td>
<td align="left">kanyon</td>
<td align="right">15.00</td>
<td align="right">30.01</td>
<td align="right">60</td>
<td align="right">90.024</td>
<td align="right">120</td>
<td align="right">0.61</td>
</tr>
<tr class="even">
<td align="left">clothing</td>
<td align="left">mall of istanbul</td>
<td align="right">15.00</td>
<td align="right">30.01</td>
<td align="right">60</td>
<td align="right">90.024</td>
<td align="right">120</td>
<td align="right">0.61</td>
</tr>
<tr class="odd">
<td align="left">clothing</td>
<td align="left">metrocity</td>
<td align="right">15.00</td>
<td align="right">30.01</td>
<td align="right">60</td>
<td align="right">90.024</td>
<td align="right">120</td>
<td align="right">0.60</td>
</tr>
<tr class="even">
<td align="left">clothing</td>
<td align="left">metropol avm</td>
<td align="right">0.00</td>
<td align="right">30.01</td>
<td align="right">60</td>
<td align="right">90.024</td>
<td align="right">120</td>
<td align="right">0.60</td>
</tr>
<tr class="odd">
<td align="left">clothing</td>
<td align="left">viaport outlet</td>
<td align="right">15.00</td>
<td align="right">30.01</td>
<td align="right">60</td>
<td align="right">90.024</td>
<td align="right">120</td>
<td align="right">0.61</td>
</tr>
<tr class="even">
<td align="left">clothing</td>
<td align="left">zorlu center</td>
<td align="right">15.00</td>
<td align="right">30.01</td>
<td align="right">60</td>
<td align="right">90.024</td>
<td align="right">120</td>
<td align="right">0.60</td>
</tr>
<tr class="odd">
<td align="left">clothing</td>
<td align="left">NA</td>
<td align="right">15.00</td>
<td align="right">30.01</td>
<td align="right">60</td>
<td align="right">60.016</td>
<td align="right">120</td>
<td align="right">0.71</td>
</tr>
<tr class="even">
<td align="left">cosmetics</td>
<td align="left">cevahir avm</td>
<td align="right">2.03</td>
<td align="right">4.07</td>
<td align="right">8</td>
<td align="right">12.198</td>
<td align="right">16</td>
<td align="right">0.60</td>
</tr>
<tr class="odd">
<td align="left">cosmetics</td>
<td align="left">emaar square mall</td>
<td align="right">2.03</td>
<td align="right">4.07</td>
<td align="right">8</td>
<td align="right">12.198</td>
<td align="right">16</td>
<td align="right">0.62</td>
</tr>
<tr class="even">
<td align="left">cosmetics</td>
<td align="left">forum istanbul</td>
<td align="right">2.03</td>
<td align="right">4.07</td>
<td align="right">8</td>
<td align="right">12.198</td>
<td align="right">16</td>
<td align="right">0.62</td>
</tr>
<tr class="odd">
<td align="left">cosmetics</td>
<td align="left">istinye park</td>
<td align="right">2.03</td>
<td align="right">4.07</td>
<td align="right">8</td>
<td align="right">12.198</td>
<td align="right">16</td>
<td align="right">0.60</td>
</tr>
<tr class="even">
<td align="left">cosmetics</td>
<td align="left">kanyon</td>
<td align="right">2.03</td>
<td align="right">4.07</td>
<td align="right">8</td>
<td align="right">12.198</td>
<td align="right">16</td>
<td align="right">0.61</td>
</tr>
<tr class="odd">
<td align="left">cosmetics</td>
<td align="left">mall of istanbul</td>
<td align="right">2.03</td>
<td align="right">4.07</td>
<td align="right">8</td>
<td align="right">12.198</td>
<td align="right">16</td>
<td align="right">0.60</td>
</tr>
<tr class="even">
<td align="left">cosmetics</td>
<td align="left">metrocity</td>
<td align="right">2.03</td>
<td align="right">4.07</td>
<td align="right">8</td>
<td align="right">12.198</td>
<td align="right">16</td>
<td align="right">0.61</td>
</tr>
<tr class="odd">
<td align="left">cosmetics</td>
<td align="left">metropol avm</td>
<td align="right">2.03</td>
<td align="right">4.07</td>
<td align="right">8</td>
<td align="right">12.198</td>
<td align="right">16</td>
<td align="right">0.62</td>
</tr>
<tr class="even">
<td align="left">cosmetics</td>
<td align="left">viaport outlet</td>
<td align="right">2.03</td>
<td align="right">4.07</td>
<td align="right">8</td>
<td align="right">12.198</td>
<td align="right">16</td>
<td align="right">0.62</td>
</tr>
<tr class="odd">
<td align="left">cosmetics</td>
<td align="left">zorlu center</td>
<td align="right">2.03</td>
<td align="right">4.07</td>
<td align="right">8</td>
<td align="right">12.198</td>
<td align="right">16</td>
<td align="right">0.64</td>
</tr>
<tr class="even">
<td align="left">cosmetics</td>
<td align="left">NA</td>
<td align="right">8.13</td>
<td align="right">9.15</td>
<td align="right">10</td>
<td align="right">11.182</td>
<td align="right">12</td>
<td align="right">0.28</td>
</tr>
<tr class="odd">
<td align="left">food &amp; beverage</td>
<td align="left">cevahir avm</td>
<td align="right">0.52</td>
<td align="right">1.05</td>
<td align="right">2</td>
<td align="right">2.092</td>
<td align="right">3</td>
<td align="right">0.48</td>
</tr>
<tr class="even">
<td align="left">food &amp; beverage</td>
<td align="left">emaar square mall</td>
<td align="right">0.52</td>
<td align="right">1.05</td>
<td align="right">2</td>
<td align="right">2.092</td>
<td align="right">3</td>
<td align="right">0.46</td>
</tr>
<tr class="odd">
<td align="left">food &amp; beverage</td>
<td align="left">forum istanbul</td>
<td align="right">0.52</td>
<td align="right">1.05</td>
<td align="right">2</td>
<td align="right">2.092</td>
<td align="right">3</td>
<td align="right">0.49</td>
</tr>
<tr class="even">
<td align="left">food &amp; beverage</td>
<td align="left">istinye park</td>
<td align="right">0.52</td>
<td align="right">1.05</td>
<td align="right">2</td>
<td align="right">2.092</td>
<td align="right">3</td>
<td align="right">0.47</td>
</tr>
<tr class="odd">
<td align="left">food &amp; beverage</td>
<td align="left">kanyon</td>
<td align="right">0.52</td>
<td align="right">1.05</td>
<td align="right">2</td>
<td align="right">2.092</td>
<td align="right">3</td>
<td align="right">0.47</td>
</tr>
<tr class="even">
<td align="left">food &amp; beverage</td>
<td align="left">mall of istanbul</td>
<td align="right">0.52</td>
<td align="right">1.05</td>
<td align="right">2</td>
<td align="right">2.092</td>
<td align="right">3</td>
<td align="right">0.48</td>
</tr>
<tr class="odd">
<td align="left">food &amp; beverage</td>
<td align="left">metrocity</td>
<td align="right">0.52</td>
<td align="right">1.05</td>
<td align="right">2</td>
<td align="right">2.092</td>
<td align="right">3</td>
<td align="right">0.47</td>
</tr>
<tr class="even">
<td align="left">food &amp; beverage</td>
<td align="left">metropol avm</td>
<td align="right">0.52</td>
<td align="right">1.05</td>
<td align="right">2</td>
<td align="right">2.092</td>
<td align="right">3</td>
<td align="right">0.47</td>
</tr>
<tr class="odd">
<td align="left">food &amp; beverage</td>
<td align="left">viaport outlet</td>
<td align="right">0.52</td>
<td align="right">1.05</td>
<td align="right">2</td>
<td align="right">2.092</td>
<td align="right">3</td>
<td align="right">0.47</td>
</tr>
<tr class="even">
<td align="left">food &amp; beverage</td>
<td align="left">zorlu center</td>
<td align="right">0.52</td>
<td align="right">1.05</td>
<td align="right">2</td>
<td align="right">2.092</td>
<td align="right">3</td>
<td align="right">0.47</td>
</tr>
<tr class="odd">
<td align="left">shoes</td>
<td align="left">cevahir avm</td>
<td align="right">60.02</td>
<td align="right">120.03</td>
<td align="right">180</td>
<td align="right">240.068</td>
<td align="right">300</td>
<td align="right">0.47</td>
</tr>
<tr class="even">
<td align="left">shoes</td>
<td align="left">emaar square mall</td>
<td align="right">60.02</td>
<td align="right">120.03</td>
<td align="right">180</td>
<td align="right">240.068</td>
<td align="right">300</td>
<td align="right">0.47</td>
</tr>
<tr class="odd">
<td align="left">shoes</td>
<td align="left">forum istanbul</td>
<td align="right">60.02</td>
<td align="right">120.03</td>
<td align="right">180</td>
<td align="right">240.068</td>
<td align="right">300</td>
<td align="right">0.44</td>
</tr>
<tr class="even">
<td align="left">shoes</td>
<td align="left">istinye park</td>
<td align="right">60.02</td>
<td align="right">120.03</td>
<td align="right">180</td>
<td align="right">240.068</td>
<td align="right">300</td>
<td align="right">0.47</td>
</tr>
<tr class="odd">
<td align="left">shoes</td>
<td align="left">kanyon</td>
<td align="right">60.02</td>
<td align="right">120.03</td>
<td align="right">180</td>
<td align="right">240.068</td>
<td align="right">300</td>
<td align="right">0.47</td>
</tr>
<tr class="even">
<td align="left">shoes</td>
<td align="left">mall of istanbul</td>
<td align="right">60.02</td>
<td align="right">120.03</td>
<td align="right">180</td>
<td align="right">240.068</td>
<td align="right">300</td>
<td align="right">0.46</td>
</tr>
<tr class="odd">
<td align="left">shoes</td>
<td align="left">metrocity</td>
<td align="right">60.02</td>
<td align="right">120.03</td>
<td align="right">180</td>
<td align="right">240.068</td>
<td align="right">300</td>
<td align="right">0.47</td>
</tr>
<tr class="even">
<td align="left">shoes</td>
<td align="left">metropol avm</td>
<td align="right">60.02</td>
<td align="right">120.03</td>
<td align="right">180</td>
<td align="right">240.068</td>
<td align="right">300</td>
<td align="right">0.47</td>
</tr>
<tr class="odd">
<td align="left">shoes</td>
<td align="left">viaport outlet</td>
<td align="right">60.02</td>
<td align="right">120.03</td>
<td align="right">180</td>
<td align="right">240.068</td>
<td align="right">300</td>
<td align="right">0.47</td>
</tr>
<tr class="even">
<td align="left">shoes</td>
<td align="left">zorlu center</td>
<td align="right">60.02</td>
<td align="right">120.03</td>
<td align="right">180</td>
<td align="right">240.068</td>
<td align="right">300</td>
<td align="right">0.46</td>
</tr>
<tr class="odd">
<td align="left">shoes</td>
<td align="left">NA</td>
<td align="right">180.05</td>
<td align="right">180.05</td>
<td align="right">180</td>
<td align="right">180.051</td>
<td align="right">180</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="left">souvenir</td>
<td align="left">cevahir avm</td>
<td align="right">1.17</td>
<td align="right">2.35</td>
<td align="right">4</td>
<td align="right">4.692</td>
<td align="right">6</td>
<td align="right">0.46</td>
</tr>
<tr class="odd">
<td align="left">souvenir</td>
<td align="left">emaar square mall</td>
<td align="right">1.17</td>
<td align="right">2.35</td>
<td align="right">4</td>
<td align="right">4.692</td>
<td align="right">6</td>
<td align="right">0.49</td>
</tr>
<tr class="even">
<td align="left">souvenir</td>
<td align="left">forum istanbul</td>
<td align="right">1.17</td>
<td align="right">2.35</td>
<td align="right">4</td>
<td align="right">4.692</td>
<td align="right">6</td>
<td align="right">0.47</td>
</tr>
<tr class="odd">
<td align="left">souvenir</td>
<td align="left">istinye park</td>
<td align="right">1.17</td>
<td align="right">2.35</td>
<td align="right">4</td>
<td align="right">4.692</td>
<td align="right">6</td>
<td align="right">0.48</td>
</tr>
<tr class="even">
<td align="left">souvenir</td>
<td align="left">kanyon</td>
<td align="right">1.17</td>
<td align="right">2.35</td>
<td align="right">4</td>
<td align="right">4.692</td>
<td align="right">6</td>
<td align="right">0.48</td>
</tr>
<tr class="odd">
<td align="left">souvenir</td>
<td align="left">mall of istanbul</td>
<td align="right">1.17</td>
<td align="right">2.35</td>
<td align="right">4</td>
<td align="right">4.692</td>
<td align="right">6</td>
<td align="right">0.46</td>
</tr>
<tr class="even">
<td align="left">souvenir</td>
<td align="left">metrocity</td>
<td align="right">1.17</td>
<td align="right">2.35</td>
<td align="right">4</td>
<td align="right">4.692</td>
<td align="right">6</td>
<td align="right">0.48</td>
</tr>
<tr class="odd">
<td align="left">souvenir</td>
<td align="left">metropol avm</td>
<td align="right">1.17</td>
<td align="right">2.35</td>
<td align="right">4</td>
<td align="right">4.692</td>
<td align="right">6</td>
<td align="right">0.47</td>
</tr>
<tr class="even">
<td align="left">souvenir</td>
<td align="left">viaport outlet</td>
<td align="right">1.17</td>
<td align="right">2.35</td>
<td align="right">4</td>
<td align="right">4.692</td>
<td align="right">6</td>
<td align="right">0.49</td>
</tr>
<tr class="odd">
<td align="left">souvenir</td>
<td align="left">zorlu center</td>
<td align="right">1.17</td>
<td align="right">2.35</td>
<td align="right">4</td>
<td align="right">4.692</td>
<td align="right">6</td>
<td align="right">0.49</td>
</tr>
<tr class="even">
<td align="left">technology</td>
<td align="left">cevahir avm</td>
<td align="right">1.05</td>
<td align="right">2.10</td>
<td align="right">3</td>
<td align="right">4.200</td>
<td align="right">5</td>
<td align="right">0.47</td>
</tr>
<tr class="odd">
<td align="left">technology</td>
<td align="left">emaar square mall</td>
<td align="right">1.05</td>
<td align="right">2.10</td>
<td align="right">3</td>
<td align="right">4.200</td>
<td align="right">5</td>
<td align="right">0.48</td>
</tr>
<tr class="even">
<td align="left">technology</td>
<td align="left">forum istanbul</td>
<td align="right">1.05</td>
<td align="right">2.10</td>
<td align="right">3</td>
<td align="right">4.200</td>
<td align="right">5</td>
<td align="right">0.49</td>
</tr>
<tr class="odd">
<td align="left">technology</td>
<td align="left">istinye park</td>
<td align="right">1.05</td>
<td align="right">2.10</td>
<td align="right">3</td>
<td align="right">4.200</td>
<td align="right">5</td>
<td align="right">0.47</td>
</tr>
<tr class="even">
<td align="left">technology</td>
<td align="left">kanyon</td>
<td align="right">1.05</td>
<td align="right">2.10</td>
<td align="right">3</td>
<td align="right">4.200</td>
<td align="right">5</td>
<td align="right">0.47</td>
</tr>
<tr class="odd">
<td align="left">technology</td>
<td align="left">mall of istanbul</td>
<td align="right">1.05</td>
<td align="right">2.10</td>
<td align="right">3</td>
<td align="right">4.200</td>
<td align="right">5</td>
<td align="right">0.47</td>
</tr>
<tr class="even">
<td align="left">technology</td>
<td align="left">metrocity</td>
<td align="right">1.05</td>
<td align="right">2.10</td>
<td align="right">3</td>
<td align="right">4.200</td>
<td align="right">5</td>
<td align="right">0.48</td>
</tr>
<tr class="odd">
<td align="left">technology</td>
<td align="left">metropol avm</td>
<td align="right">1.05</td>
<td align="right">2.10</td>
<td align="right">3</td>
<td align="right">4.200</td>
<td align="right">5</td>
<td align="right">0.46</td>
</tr>
<tr class="even">
<td align="left">technology</td>
<td align="left">viaport outlet</td>
<td align="right">1.05</td>
<td align="right">2.10</td>
<td align="right">3</td>
<td align="right">4.200</td>
<td align="right">5</td>
<td align="right">0.47</td>
</tr>
<tr class="odd">
<td align="left">technology</td>
<td align="left">zorlu center</td>
<td align="right">0.00</td>
<td align="right">2.10</td>
<td align="right">3</td>
<td align="right">4.200</td>
<td align="right">5</td>
<td align="right">0.47</td>
</tr>
<tr class="even">
<td align="left">technology</td>
<td align="left">NA</td>
<td align="right">2.10</td>
<td align="right">2.62</td>
<td align="right">3</td>
<td align="right">3.675</td>
<td align="right">4</td>
<td align="right">0.47</td>
</tr>
<tr class="odd">
<td align="left">toys</td>
<td align="left">cevahir avm</td>
<td align="right">1.79</td>
<td align="right">3.58</td>
<td align="right">7</td>
<td align="right">10.752</td>
<td align="right">14</td>
<td align="right">0.61</td>
</tr>
<tr class="even">
<td align="left">toys</td>
<td align="left">emaar square mall</td>
<td align="right">1.79</td>
<td align="right">3.58</td>
<td align="right">7</td>
<td align="right">10.752</td>
<td align="right">14</td>
<td align="right">0.59</td>
</tr>
<tr class="odd">
<td align="left">toys</td>
<td align="left">forum istanbul</td>
<td align="right">1.79</td>
<td align="right">3.58</td>
<td align="right">7</td>
<td align="right">10.752</td>
<td align="right">14</td>
<td align="right">0.63</td>
</tr>
<tr class="even">
<td align="left">toys</td>
<td align="left">istinye park</td>
<td align="right">1.79</td>
<td align="right">3.58</td>
<td align="right">7</td>
<td align="right">10.752</td>
<td align="right">14</td>
<td align="right">0.61</td>
</tr>
<tr class="odd">
<td align="left">toys</td>
<td align="left">kanyon</td>
<td align="right">1.79</td>
<td align="right">3.58</td>
<td align="right">7</td>
<td align="right">10.752</td>
<td align="right">14</td>
<td align="right">0.62</td>
</tr>
<tr class="even">
<td align="left">toys</td>
<td align="left">mall of istanbul</td>
<td align="right">1.79</td>
<td align="right">3.58</td>
<td align="right">7</td>
<td align="right">10.752</td>
<td align="right">14</td>
<td align="right">0.60</td>
</tr>
<tr class="odd">
<td align="left">toys</td>
<td align="left">metrocity</td>
<td align="right">1.79</td>
<td align="right">3.58</td>
<td align="right">7</td>
<td align="right">10.752</td>
<td align="right">14</td>
<td align="right">0.59</td>
</tr>
<tr class="even">
<td align="left">toys</td>
<td align="left">metropol avm</td>
<td align="right">1.79</td>
<td align="right">3.58</td>
<td align="right">7</td>
<td align="right">10.752</td>
<td align="right">14</td>
<td align="right">0.60</td>
</tr>
<tr class="odd">
<td align="left">toys</td>
<td align="left">viaport outlet</td>
<td align="right">1.79</td>
<td align="right">3.58</td>
<td align="right">7</td>
<td align="right">10.752</td>
<td align="right">14</td>
<td align="right">0.62</td>
</tr>
<tr class="even">
<td align="left">toys</td>
<td align="left">zorlu center</td>
<td align="right">1.79</td>
<td align="right">3.58</td>
<td align="right">7</td>
<td align="right">10.752</td>
<td align="right">14</td>
<td align="right">0.58</td>
</tr>
<tr class="odd">
<td align="left">toys</td>
<td align="left">NA</td>
<td align="right">1.79</td>
<td align="right">1.79</td>
<td align="right">2</td>
<td align="right">1.792</td>
<td align="right">2</td>
<td align="right">NA</td>
</tr>
</tbody>
</table>
<p>Para imputar los datos faltantes del precio se transformó el precio a escala logarítmica y se imputó mediante predictive mean matching con <code>mice</code>, empleando la categoría del producto y cantidad (1 – 5 codificada como factor ordinal) como predictores fijos. Para cada precio ausente el algoritmo seleccionó al azar uno de los tres valores observados más parecidos dentro de la misma categoría (matchgroup), y la opción <code>bounded</code> garantizó que el imputado quedara dentro del rango mínimo–máximo observado de ese grupo. Se generaron 15 conjuntos imputados con 10 iteraciones cada uno, suficientes para alcanzar la convergencia dado que solo el precio presentaba faltantes. Los precios imputados se retransformaron con <code>exp()</code> y se verificó gráficamente que la distribución por categoría se mantiene sin valores extremos artificiales.</p>
<p>En las Figuras <a href="procesamiento.html#fig:figPreciocategory2">5.8</a> y <a href="procesamiento.html#fig:figPreciocategoryImp2">5.9</a> comparativas de densidades, la gráfica original (antes de imputar) muestra picos de menor altura; tras la imputación, los picos se elevan pero permanecen exactamente en las mismas posiciones de precio, señal de que el algoritmo bounded PMM copió valores observados sin introducir nuevos niveles. Así, la imputación complementa las frecuencias faltantes respetando la distribución de cada categoría.</p>
<div class="figure"><span style="display:block;" id="fig:figPreciocategory2"></span>
<img src="Informe-descriptivo_files/figure-html/figPreciocategory2-1.png" alt="Distribución del precio (se muestran en miles) según  categoría antes de la imputación." width="672" />
<p class="caption">
Figure 5.8: Distribución del precio (se muestran en miles) según categoría antes de la imputación.
</p>
</div>
<div class="figure"><span style="display:block;" id="fig:figPreciocategoryImp2"></span>
<img src="Informe-descriptivo_files/figure-html/figPreciocategoryImp2-1.png" alt="Distribución del precio (se muestran en miles) según  categoría después de la imputación." width="672" />
<p class="caption">
Figure 5.9: Distribución del precio (se muestran en miles) según categoría después de la imputación.
</p>
</div>
<p>Los boxplots de las Figuras <a href="procesamiento.html#fig:figPreciocategory1">5.10</a> y <a href="procesamiento.html#fig:figPreciocategoryImp1">5.11</a> muestran que la imputación multiplicó el número de observaciones en cada categoría sin introducir valores fuera de los límites reales ni distorsionar las posiciones de la mediana. Las cajas son un poco más anchas, señal de que ahora se refleja mejor la variabilidad subyacente, pero la jerarquía de precios entre categorías (shoes ≫ clothing ≫ books, etc.) permanece intacta. Esto confirma que el método bounded PMM con donantes dentro de la misma categoría preservó la estructura original de los datos mientras completaba los valores faltantes.</p>
<div class="figure"><span style="display:block;" id="fig:figPreciocategory1"></span>
<img src="Informe-descriptivo_files/figure-html/figPreciocategory1-1.png" alt="Distribución del precio (se muestran en miles) según  categoría antes de la imputación." width="672" />
<p class="caption">
Figure 5.10: Distribución del precio (se muestran en miles) según categoría antes de la imputación.
</p>
</div>
<div class="figure"><span style="display:block;" id="fig:figPreciocategoryImp1"></span>
<img src="Informe-descriptivo_files/figure-html/figPreciocategoryImp1-1.png" alt="Distribución del precio (se muestran en miles) según  categoría después de la imputación." width="672" />
<p class="caption">
Figure 5.11: Distribución del precio (se muestran en miles) según categoría después de la imputación.
</p>
</div>
</div>
<div id="imputación-de-la-edad-age" class="section level3 hasAnchor" number="5.4.2">
<h3><span class="header-section-number">5.4.2</span> Imputación de la Edad (age)<a href="procesamiento.html#imputación-de-la-edad-age" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>La variable Edad presenta una distribución prácticamente uniforme entre los 18 y los 69–70 años; en otras palabras, cualquier valor dentro de ese intervalo es casi igual de probable. Utilizar la media o la mediana como valor único de reemplazo concentraría todos los casos faltantes en el centro y generaría un pico artificial que no existe en los datos reales. Para evitar ese sesgo se optó por una imputación aleatoria simple: cada observación con <code>NA</code> recibe un valor extraído al azar, con probabilidad constante, dentro del rango 18–70 años.</p>
<p>La Figura <a href="procesamiento.html#fig:figedaddensidad">5.12</a> compara las densidades de Edad antes y después de la imputación. Las dos curvas prácticamente se superponen, lo que confirma que el procedimiento preserva la forma original de la distribución —no introduce picos espurios ni distorsiona la frecuencia relativa de los distintos tramos de edad— y, por tanto, mantiene la representatividad de la muestra para análisis posteriores.</p>
<div class="figure"><span style="display:block;" id="fig:figedaddensidad"></span>
<img src="Informe-descriptivo_files/figure-html/figedaddensidad-1.png" alt="Distribución de edad antes y después de la imputación." width="672" />
<p class="caption">
Figure 5.12: Distribución de edad antes y después de la imputación.
</p>
</div>
</div>
<div id="imputación-de-sexo-gender-centro-comercial-shopping_mall-y-método-de-pago-payment_method" class="section level3 hasAnchor" number="5.4.3">
<h3><span class="header-section-number">5.4.3</span> Imputación de Sexo (gender), Centro Comercial (shopping_mall) y Método de pago (payment_method)<a href="procesamiento.html#imputación-de-sexo-gender-centro-comercial-shopping_mall-y-método-de-pago-payment_method" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Los datos faltantes de las variables <em>Sexo</em>, <em>Centro comercial</em> y <em>Método de pago</em> son imputados usando la moda de cada una de las variables.</p>
<p>La Figura <a href="procesamiento.html#fig:figimpSCCM">5.13</a> muestra la distribución estas variables antes y después de la imputación de los datos. Ambas distribuciones se aprecian muy parecidas, lo que es una buena señal para continuar con el análisis.</p>
<div class="figure"><span style="display:block;" id="fig:figimpSCCM"></span>
<img src="Informe-descriptivo_files/figure-html/figimpSCCM-1.png" alt="Distribución de Sexo, Centro comercial y Método de pago." width="672" />
<p class="caption">
Figure 5.13: Distribución de Sexo, Centro comercial y Método de pago.
</p>
</div>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="datos.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="resultados.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
